### ISSUE TITLE
Adapt IO column parsing logic to new `Input[X] / Output[Y]` headers

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/ARCTokenization#25]
after the big updates surrounding arctrl, there will also be a new, more flexible input/output column syntax. See this issue:

https://github.com/nfdi4plants/Swate/issues/316#issuecomment-1645565194

Since we partition the columns into IO vs rest, we just need to update our regexes accordingly, so let this issue stand here as a reminder to do that eventually.

**Comment by HLWeil** [comment]
On it currently. Will link another issue.

**Comment by kMutagene** [comment]
Not relevant anymore since https://github.com/nfdi4plants/ARCTokenization/pull/48 is merged
