### ISSUE TITLE
Investigation Ontology: STUDY misses some `follows` relationships

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/ARCTokenization#31]
https://github.com/nfdi4plants/ARCTokenization/blob/2dfd46f6884a61853baa76971620e868b66b4987/src/ARCTokenization/structural_ontologies/investigation_metadata_structural_ontology.obo#L243-L248

As seen here

![image](https://github.com/nfdi4plants/ARCTokenization/assets/47781170/ebe237a8-fbf4-434e-abf5-4d8ddc4cc1ce), 
STUDY can also follow Study Person Roles Term Source REF (for every Study added to an Investigation after the first one). This is not mapped atm. in Investigation Metadata ontology.

Image's source file: https://git.nfdi4plants.org/muehlhaus/ArcPrototype/-/blob/main/isa.investigation.xlsx

---

Also misses `follows` to Investigation Person ORCID:

![image](https://github.com/nfdi4plants/ARCTokenization/assets/47781170/42a25a01-87d0-49e8-8713-d34ad77ce0f2)
(same source as above)

**Comment by kMutagene** [comment]
should be fixed via https://github.com/nfdi4plants/ARCTokenization/commit/587eafb4a0e023a29eaa58edf63231a272e4aa60
